
title = "blog"
explain = "code.sun个人blog"
mode = "dev"
addr = ":9088"
srv = "https://blog.feibooks.com"

# token 相关
token_key = "token"
# 过期时间 h
token_exp = 24
# 单点登录
token_sso =false
# 保持在线
token_keep = false
# 加密私钥
token_secret ="secret"

# 系统
# 图片裁剪
image_cut = false
image_width = 800
image_height =600
# 分页
page_min = 5
page_max = 30

# 数据库
# https://github.com/go-sql-driver/mysql
# 数据库地址
db_kind = "sqlite"
db_sqlite_src = "data/goblog.db"
db_host = "127.0.0.1"
# 数据库端口
db_port = 3306
# 数据库账号
db_user = "root"
# 数据库密码
db_passwd = "mysql123456"
# 数据库名称
db_name = "goblog"
# 数据库参数
db_params = "charset=utf8mb4&parseTime=true&loc=Local"

# orm
# https://gitea.com/xorm/xorm
# 推荐cpu核心数
orm_idle = 4
# 推荐cpu核心数*2
orm_open = 8
# 显示sql
orm_show = true
# 同步表结构
orm_sync = true
# 是否使用orm缓存
orm_cache_use = false
# orm缓存数量
orm_cache_size = 1000
# orm劫持日志输出
orm_hijack_log = true

# 作者
[author]
name = "code.sun"
website = "https://github.com/kms9"

# 微信相关
# 公众号 小程序 https://mp.weixin.qq.com/
# H5 网站 https://open.weixin.qq.com/cgi-bin/index
[wechat]
# 公众号
# 请同时修改 conf.go
gzh_appid = "appid"
gzh_secret = "secret"
# 小程序
mpg_appid = "appid"
mpg_secret = "secret"
# web
web_appid = "appid"

